### PR TITLE
Add an app built with Next.js & hosted with Firebase

### PR DESCRIPTION
**Pull request by kulshekhar**
Lighthouse: [91 98 100 100](https://www.webpagetest.org/lighthouse.php?test=170924_SG_e20c408039688ecdcc07205ff6a91299&run=2)
Interactive (Emerging Markets): [2.7s](https://www.webpagetest.org/result/170924_BQ_08b80e1854f5bfa0c5b36d10a5373b1e/)
Interactive (Faster 3G): [2.2s](https://www.webpagetest.org/result/170924_SG_e20c408039688ecdcc07205ff6a91299/)

App: https://next-fb-hnpwa.firebaseapp.com/
Repo: https://github.com/kulshekhar/next-hnpwa

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
So sorry for not getting back to you sooner @kulshekhar :( We're in the process of approving/clearing submissions now and getting things back on track.

The app link is currently down so I can't review it at the moment. If you happen to still be interested in landing this submission, please let me know and I'll reopen this!

**Comment by kulshekhar** [comment]
This is weird. It seems to be working now despite nothing being done to address it.

**Comment by housseindjirdeh** [comment]
No worries at all mate, sorry for not looking at this much much sooner.

Yeah I'm still seeing the same problem 🤔 

screen shot 2018-07-01 at 8 42 33 pm

For this application, are you using anything from Firebase besides it's hosting by any chance?

**Comment by kulshekhar** [comment]
The app uses firebase hosting and firebase functions. It also fetches details from `https://hacker-news.firebaseio.com`

The screenshot you've pasted is the exact error I saw yesterday. I've been unable to replicate it and it seems to be working fine today. I suspect that fetching the data from the other URL might be causing this.

**Comment by housseindjirdeh** [comment]
Yeah I googled the error and it seems that a few folks were seeing similar messages using Functions

https://stackoverflow.com/questions/47479400/firebase-function-http-trigger-error-could-not-handle-the-request-firebase?rq=1

Any chance you can take a look at the logs (`firebase functions:log`) in case there's another intermittent issue? You might be right however and it could be fetching data from the URL that's surfacing this error.

**Comment by kulshekhar** [comment]
@housseindjirdeh nailed it.

```
Error: quota exceeded (Function invocations : per day)
```

The same app is also hosted with heroku (https://next-hnpwa.herokuapp.com/). Would that be sufficient to evaluate it?

**Comment by kulshekhar** [comment]
I've also left a request to increase the quota but I'm not sure how that will be received.

**Comment by housseindjirdeh** [comment]
Absolutely! Thank you for deploying it to heroku as well 🙏 

Running newer WPT traces and TTI numbers look outstanding 👍 

Regular 3G: https://www.webpagetest.org/lighthouse.php?test=180704_Z3_26cf2163568416fcfe91d322577bfb1b&run=3
Slow 3G: https://www.webpagetest.org/lighthouse.php?test=180704_19_8728b9a5c9ade20877897631581b9fe8&run=1

App looks great on mobile, works well offline with dynamic content cached as well as the assets that make up an App Shell

This LGTM!! :shipit:

**Comment by housseindjirdeh** [comment]
First Byte Time is looking like it can be improved however (not necessary to land this in though!). 

screen shot 2018-07-03 at 8 40 09 pm

Maybe you can consider hosting on Netlify to improve that?

**Comment by kulshekhar** [comment]
@housseindjirdeh thank you so much for taking another look and merging this in!

I haven't used Netlify yet but I'll give that a shot over the weekend and try to host this app there. Thanks for the suggestion

**Pull request merged**
