### PR TITLE
Add Polymer to PWA list

### PR DESCRIPTION
**Pull request by azakus**
Here's a Polymer 2 version of the HackerNews PWA!

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
This is awesome :heart_eyes: 

Don't forgot to add yourself as a [contributor](https://github.com/tastejs/hacker-news-pwas/tree/master/site/_contributors) too :)

**Comment by addyosmani** [comment]
This is _so_ well done. Fantastic work, Steve, Kevin and Dan. I really appreciate the hard work getting this out.

Could you follow this up with a PR adding yourselves as contributors to the homepage? :)

**Comment by addyosmani** [comment]
We'll get this deployed shortly.

**Comment by azakus** [comment]
Contributor PR in #31

**Pull request merged**
