### PR TITLE
Add HNPWA - Mithril HN implementation

### PR DESCRIPTION
**Pull request by chimon2000**
Implementation using Mithril

### CODE REVIEW

**Comment by gyandeeps** [comment]
I did not know @chimon2000 that you were working on mithril. I actually started working on this few weeks back and logged an issue https://github.com/tastejs/hacker-news-pwas/issues/56. 
So not sure if I should continue or stop. Mine is pure javascript.

**Comment by chimon2000** [comment]
@kristoferbaxter I'll be glad to make those changes. 

I've never used WebPageTest before so I was unsure about the right number.  Is it **first interactive** that I should be looking at?

**Comment by chimon2000** [comment]
@gyandeeps I don't think that it's a "one and done" scenario.  There are a couple of Vue/React examples up. Personally, I'd welcome another Mithril example since it was my first time using the framework.

**Comment by housseindjirdeh** [comment]
@chimon2000 that is correct. You can run the tests using webpagetest.org/easy for both Faster 3G and EM settings with the Lighthouse Audit checked. Once your test completes, you can click the Lighthouse score to navigate to its associated report with which First Interactive is the time we use for all of the implementations on the site.

And yes @gyandeeps please carry on with your implementation! We're not too concerned it's having multiple examples of clients built with the same framework, more is always merrier  :)

**Comment by addyosmani** [comment]
Just adding another "more implementations matching requirements are always welcome" note :) We've already seen some approaches (e.g @kristoferbaxter's ReactHN take) out-perform others using a different approach to architecture so I'm not worried about us having multiple apps for each framework.

**Comment by chimon2000** [comment]
@kristoferbaxter changes up.
@housseindjirdeh thanks for clarifying!

**Comment by kristoferbaxter** [comment]
Looks good to me.

**Comment by reccanti** [comment]
@gyandeeps I also started working on a Mithril PWA (though I didn't get super far on it). Need any help?

**Comment by gyandeeps** [comment]
sure @reccanti . I have already opened a PR https://github.com/tastejs/hacker-news-pwas/pull/76 ... feel free to contribute in any fashion u like. Appreciate it..

**Pull request merged**
