### PR TITLE
add apprun-hn

### PR DESCRIPTION
**Pull request by yysun**

### CODE REVIEW

**Comment by yysun** [comment]
Thank you @housseindjirdeh for the review. I have made the UI changes.

**Comment by housseindjirdeh** [comment]
Thanks @yysun, appreciate you getting to the changes so quickly!

I'm still seeing the older version with nested story items + multiple links in the app header

screen shot 2018-07-09 at 10 49 30 pm

Did you forget to deploy your changes by any chance?

**Comment by yysun** [comment]
Maybe it is cached by the service worker. When I was deploying and testing, I had to unregister the service worker. Can you try?

**Comment by housseindjirdeh** [comment]
Hmmm I thought that must have been the case and probably forgot to clear my cache/unregister the sw, but I'm still seeing it when I do that 🤔 

screen shot 2018-07-12 at 8 10 38 pm

Interestingly enough. I don't see this behaviour on Firefox or Chrome. I also know that it can't be the older cached version showing for me on Chrome because I'm seeing the update you applied to the top link on the left. So I'm definitely looking at an updated version of the site.

And to make things more interesting 😂 I don't see list items being indented in device previews with DevTools

screen shot 2018-07-12 at 8 10 56 pm

And I just asked my brother to pop up the site on his machine and it looks just fine for him on Chrome.

I've never seen anything like this (and can't even spot anything CSS specific you've done that would warrant different behaviour on different browsers). 

Just want to ask, does it render fine for yourself on Chrome? If so, let's just land this in! I can further investigate things on my end to see why I'm still seeing the issue.

**Comment by yysun** [comment]
Thank you again @housseindjirdeh and your brother. It does render fine in Chrome here.

image

BTW, I noticed in your screenshot, there is an extra script named db794a8b-... Also the screen capture does not stop. Is it a problem?

In my Chrome, the screen capture stops.

**Comment by housseindjirdeh** [comment]
Ah good call, that script seems to be injected by one of my chrome extensions (which is kind of bizarre/worrisome to be honest). Removed it entirely. 

New screenshot runs:

screen shot 2018-07-12 at 9 38 54 pm

For screen capture do you mean the filmstrips? Sorry if my earlier screenshot was cropped too small! The app finished loading if that's what you were wondering.

----

Sorry for dragging this discussion for this tiny thing I'm only noticing. I think we're good to land this now! 🚀 🚀 🚀

**Pull request merged**
