### PR TITLE
Add HNPWA -  RE:DOM implementation

### PR DESCRIPTION
**Pull request by chimon2000**
Implementation using RE:DOM

### CODE REVIEW

**Comment by cheeaun** [comment]
Hmm not sure if you should use RE:DOM's logo as part of the site logo though 🤔

**Comment by chimon2000** [comment]
@cheeaun could remove, was just copying the same pattern as my previous entry and some of the other entries.

**Comment by addyosmani** [comment]
Thanks for the submission! Perf numbers LGTM. 

UX Feedback:

Homepage/top-stories appears to be implemented as a "load more" list instead of using visible pagination. For consistency with the other apps, could you consider switching to pagination like the following apps have?

https://react-hn.kristoferbaxter.com/
https://hn.kristoferbaxter.com/
https://hn.svelte.technology/

image

**Comment by addyosmani** [comment]
@chimon2000 It's been a while since we heard back. Are you still interested in working on this? We can close if not, but happy to keep open otherwise 🍪

**Comment by addyosmani** [comment]
As it's been a few quarters since we last heard anything on this PR, we're going to go ahead with closing it. We really appreciate the effort to contribute here. If you would like to try contributing this application back once more, please feel free to open up a new PR addressing previous feedback and we will reconsider it.

**Pull request closed without merging**
