### PR TITLE
Added CycleJS implementation of HN client

### PR DESCRIPTION
**Pull request by usm4n**
A [cycle.js](https://github.com/cyclejs/cyclejs/) implementation of the Hacker News client.

Git repository: https://github.com/usm4n/cycle-hn
Demo: https://cyclejs-hn.firebaseapp.com

Also I was not sure about the `weight` property, so I went ahead and filled it with an incremented number. Please let me know if I am missing something.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR, @usm4n. First piece of feedback on this one is can we adjust the pagination UI to follow the pattern in https://hn.kristoferbaxter.com/? e.g rather than a `more` having clear prev/next navigation. 

Started digging into perf here and it mostly looks good. There is some minor discrepancy in what WPT and Lighthouse are reporting but I'll dig into that further.

**Comment by usm4n** [comment]
@addyosmani thank you for looking into this. Yes I will definitely change the `more` to `next/prev` pattern. Please let me know any thing else that needs to be fixed or changed.

**Comment by usm4n** [comment]
A little ping :) to notify that I have made the required changes to the application's pagination.

**Comment by addyosmani** [comment]
Thanks for the ping, @usm4n! Taking another look now.

**Comment by addyosmani** [comment]
@usm4n I'm not seeing this set of changes in the current deployment at https://cyclejs-hn.firebaseapp.com. Were they pushed? 

Some other feedback: on desktop, it would be great if we centered the content rather than stretching it to take up the entire width of the viewport. See https://viperhtml-164315.appspot.com/top/1 for an example.

**Comment by usm4n** [comment]
@addyosmani yes definitely I had pushed the changes to the firebase hosting.

Anyways I have made the new changes as required and pushed them to the firebase hosting. 

The newly deployed app can be accessed with the following URLs:

https://cyclejs-hn.firebaseapp.com/
https://cycle-hn.now.sh/

Here is the screenshot for reference:
cycle-hn

Thank you for your time :)

**Comment by usm4n** [comment]
Another update from my side is that I re-ran the WPT using the 3gSlow and 3gFast services a couple of time this morning, the results now look significantly consistent as compared to the previous test results:

[3G Fast](https://www.webpagetest.org/result/171123_ZZ_ff5766776f0308d538c34dc64292bb01/) --> 2.468s
[Filmstrip](https://www.webpagetest.org/video/compare.php?tests=171123_ZZ_ff5766776f0308d538c34dc64292bb01-r:1-c:0) --> 2.3s
[Lighthouse](https://www.webpagetest.org/lighthouse.php?test=171123_ZZ_ff5766776f0308d538c34dc64292bb01&run=1) --> 2.3s

[3G Slow](https://www.webpagetest.org/result/171123_SV_aff949f86b7f30d41e64c4a602b61c8f/) --> 5.290s
[Filmstrip](https://www.webpagetest.org/video/compare.php?tests=171123_SV_aff949f86b7f30d41e64c4a602b61c8f-r:1-c:0) --> 6.0s
[Lighthouse](https://www.webpagetest.org/lighthouse.php?test=171123_SV_aff949f86b7f30d41e64c4a602b61c8f&run=3) --> 5.3s

Should I update these times on the PR?

**Comment by usm4n** [comment]
Friendly ping @addyosmani!

Just wondering if I could get your review on these last updates.

**Comment by addyosmani** [comment]
@usm4n I just conducted another UX review and the Firebase deploy is looking solid. If you'd like to go ahead and update the application weight (use 27 please as 26 has landed) and the above updated WebPageTest numbers we should be able to get this landed shortly.

**Comment by usm4n** [comment]
@addyosmani, I have updated the scores and weight as required.

**Comment by usm4n** [comment]
@addyosmani just a friendly nudge :) to ask, if you have time to get this pulled? Of course if every thing checks out.

**Comment by addyosmani** [comment]
Sorry for the delays on getting this one landed! I'll go ahead with some minor edits to weights and get it merged.

**Pull request merged**
