### PR TITLE
Update App Images + lazy loading

### PR DESCRIPTION
**Pull request by housseindjirdeh**
This PR:

- Adds Nexus 5X phone outlines for all devices + adds note to instructions to take screenshots using this device preset in DevTools
- Updates all implementation images with Nexus 5X sizes (and compressed them)
- Includes lazysizes to lazy load all app + author images
- Updates service worker config to cache image assets on scroll and not pre-cache them as soon as the page loads

Can view all the updates here: https://bananaflipflops.surge.sh/

screen shot 2018-07-15 at 11 38 05 am

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Worth considering a few styles when images fail to be retrieved?

screen shot 2018-07-16 at 9 22 57 am

Also, could be worth looking at an animation for when images finish downloading.

[lazy-load.zip](https://github.com/tastejs/hacker-news-pwas/files/2198454/lazy-load.zip)

**Comment by housseindjirdeh** [comment]
Good point 🙌 Will add some styles for when images fail.

And yeah you're right it makes sense to add some sort of indicator while it's loading. I considered adding low quality versions of each image that blur on scroll (like [this](https://jsfiddle.net/trixta/v0oq0412/embedded/result/)) but thought it wouldn't be very useful/maintainable to have folks upload low quality versions of their screenshots. I'll either add some CSS animation (or one low quality image that can work as a placeholder for all images).

**Comment by housseindjirdeh** [comment]
@kristoferbaxter added a few styles for loading/error states:

#### Img alt styling on error:

screen shot 2018-07-18 at 1 05 38 pm

Unfortunately this doesn't show on Safari (alt text never shows, it's just the "blue box")

#### While loading

loading-state

Let me know if you think this looks alright 🙌 

Can view here: https://strawberryshoes.surge.sh

**Comment by housseindjirdeh** [comment]
❤️

**Pull request merged**
