### PR TITLE
Ensure index.html is available on prod

### PR DESCRIPTION
**Pull request by chrisdwheatley**
The path `/index.html` needs adding to the list of available assets I believe.

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
You're a wizard @chrisdwheatley <3

**Comment by housseindjirdeh** [comment]
@chrisdwheatley 🎉 🎉 🎉 

screen shot 2017-05-18 at 1 10 23 pm

**Comment by chrisdwheatley** [comment]
Got there in the end! 🎉

screen shot 2017-05-18 at 18 09 31

screen shot 2017-05-18 at 18 10 02

**Comment by chrisdwheatley** [comment]
Posted our comments 8 seconds apart @housseindjirdeh 😀

**Comment by housseindjirdeh** [comment]
Haha classic, great minds think alike :P

**Pull request merged**
