### PR TITLE
add angular-hacker-news

### PR DESCRIPTION
**Pull request by SebastianM**
This is a SSR rendered version built with Angular 4.
Blog post here: https://sebastian-mueller.net/post/angular-hacker-news-pwa/

### CODE REVIEW

**Comment by addyosmani** [comment]
@housseindjirdeh Would love a second look from you whenever you get a chance. Just for a sanity check as it's another Angular implementation.

**Comment by anubhav7495** [comment]
@SebastianM There are a couple of bugs I found in the application

1. Comments view returns error on refreshing the page.
2. Ask HN links redirect back to `/list/top` view.

I spotted these issues here: https://angularhn.sebastian-mueller.net

**Comment by addyosmani** [comment]
Thanks for sharing feedback about those issues @anubhav7495. Clearly I should have been more careful with verifying the refresh behavior on the comments page and those redirects.

@SebastianM I've switched this up to a needs-work - could you re-ping the thread once you've had a chance to address the above?

**Comment by housseindjirdeh** [comment]
@anubhav7495 thanks so much for pinpointing those issues.

Aside from those, everything else LGTM. This is a great app @SebastianM and I can't wait to have this merged in 🎉

**Comment by SebastianM** [comment]
Thank you guys for taking the time reviewing it! 👍 
I just deployed a new version for all the findings.

@addyosmani PTAL - I also minified the app screenshot of this PR.

**Comment by addyosmani** [comment]
Great work, @SebastianM! Just took a look through and I believe we're good to go now. 

@anubhav7495 it looks like on latest your feedback has been addressed. Would you mind verifying you're happy with the current state?

**Comment by anubhav7495** [comment]
`2. Ask HN links redirect back to /list/top view when clicked.`
I can still reproduce this. 

@SebastianM!  Everything else is just perfect.

**Comment by SebastianM** [comment]
@anubhav7495 thanks for the review! I cannot reproduce it on my side (iOS/Iphone 6/Safari Mobile & Chrome). What Browser/Device are you using?

**Comment by anubhav7495** [comment]
#### Chrome 59 on Ubuntu 16.04LTS

angular-hn

**Comment by SebastianM** [comment]
@anubhav7495 Thanks! Now I know what you mean. I could reproduce it and fixed it - new version is live.

**Comment by anubhav7495** [comment]
@SebastianM there is an edge case here. 

ASK HN links in `top` or `new` list still behave the same way. In `ask` list they are working correctly now.

**Comment by SebastianM** [comment]
@anubhav7495 oh yeah you're right, good catch. Fixed it now for both scenarios.

**Comment by anubhav7495** [comment]
@SebastianM perfect man!

@addyosmani all clear from my side now.

**Comment by addyosmani** [comment]
👍

**Pull request merged**
