### PR TITLE
fix reference to use auto-selected Faster 3G setting

### PR DESCRIPTION
**Pull request by housseindjirdeh**
Just noticed that the higher TTI numbers you were noticing with Angular 2 HN last night (https://www.webpagetest.org/result/170413_25_8MA/) was with Emerging Markets :)

Changed the reference in the README to use the Faster 3G setting instead. However do you think EM should be the requirement instead? Unfortunately my app (and I think a few of the others 🤔 ) will most probably have TTI > 5s under that condition.

### CODE REVIEW

**Comment by addyosmani** [comment]
I think everything should be using the EM setting to get as close to real-world 3G as possible. Let me do a few re-runs of the others to see how far off the Lighthouse TTI audit that takes them.

**Comment by addyosmani** [comment]
Update on this: How would you feel about listing the TTI on (fast) 3G _and_ EM next to each implementation? This might get around the subtlety of some sites targeting specific markets with better faster networks than others.

**Comment by housseindjirdeh** [comment]
:+1: Yes that makes perfect sense. Updated this PR to have all the 3G and EM Webpagetests and TTIs for each implementation.

**Comment by addyosmani** [comment]
Dude. You just saved me like 30m of time :) I figured you'd just update the Angular entry with new results, but it was so kind of you to go through and re-run each of those implementations and summarize their TTI values in the README. 

Thanks a whole bunch!

giphy

**Pull request merged**
