### PR TITLE
Revert "Add another React HN implementation"

### PR DESCRIPTION
**Pull request by addyosmani**
Reverts tastejs/hacker-news-pwas#73

@stephenkingsley Backing this implementation out until the scores are fixed. I'm unsure what's happening with the current deploy, but the scores now appear to have heavily dropped (e.g 64/100 here: https://www.webpagetest.org/lighthouse.php?test=170824_P9_1f1125fe53eec08c2e766d54544c62d8&run=2)

Could you let us know once this has been fixed and we'll re-evaluate?

### CODE REVIEW

**Comment by stephenkingsley** [comment]
@addyosmani I think it was fixed.

image

yesterday, I modified the `mainfest.json`. I think this version is stable. If I will add some features, I will deploy other host first.

**Comment by addyosmani** [comment]
@stephenkingsley I'm seeing an 82/100 now. Any chance that 512px image can get fixed too?

**Comment by stephenkingsley** [comment]
@addyosmani may be tonight? I want you can push my app in the website, can you?

**Comment by stephenkingsley** [comment]
@addyosmani I fix the 512px now! [https://www.webpagetest.org/lighthouse.php?test=170826_0V_8516618e5aaa2650da5aabbc773c8929&run=3](https://www.webpagetest.org/lighthouse.php?test=170826_0V_8516618e5aaa2650da5aabbc773c8929&run=3)

**Pull request merged**
