### PR TITLE
Add HNPWA Firebase Hosting

### PR DESCRIPTION
**Pull request by davideast**
An HNPWA implementation on Firebase Hosting. Just HTML and CSS, CDN cached around the world.

- [https://hnpwa-firebase.firebaseapp.com](https://hnpwa-firebase.firebaseapp.com)
- [EM: 1.3!](https://www.webpagetest.org/result/170712_FR_5ea158fd9c684d6d8dee49f833093289/)
- [3G: 0.7!](https://www.webpagetest.org/result/170712_88_101P/)
- [Lighthouse: 98 (perf)](https://www.webpagetest.org/lighthouse.php?test=170712_FR_5ea158fd9c684d6d8dee49f833093289&run=2)

### CODE REVIEW

**Comment by cristianbote** [comment]
This is awesome! It's amazing how much you can do with just a few lines of code. Great job!

**Comment by addyosmani** [comment]
Thanks for the PR, @davideast. Those numbers look great. I'll take a deeper look into this later. Some initial UX feedback:

**Responsive UX**

Similar to the vanilla app, looks great on mobile but on desktop, stretching to the width of the viewport makes it a little more work to get the cursor all the way over to the left of the screen. I wonder if it would make sense to adopt responsive margins like some of these implems do:

https://react-hn.kristoferbaxter.com/
https://hn.kristoferbaxter.com/
https://hn.svelte.technology/
https://vue-hn.now.sh/top 

**Pagination UX**

Atm a prev/next is exposed when trying to navigate through top stories. Could we adopt showing what the current page is inline similar to some of the other apps?

image

**Offline**

Offline appears to be working as expected 👍 Awesome work.

However as you're purely server-side rendering you're full-page caching all of the pages. Our requirements state that apps need to be using the [AppShell](https://github.com/tastejs/hacker-news-pwas#specification) pattern. 

I would like us to try landing the app, but if we do we would need to either expand our requirements or distinguish this app from the others to make sure the faster scores are presented in the context of "this is just doing SSR instead of the SSR + AppShell some of the other apps are using". Does that make sense?

**Comment by davideast** [comment]
@addyosmani No problem on fixing the viewport sizing and paging (got lazy last night with the numbering).

As far as offline goes, I'd like to initially submit this as a comparison to the rest. A traditional AppShell would actually slow down the page load. I'm going to continue to work on adding the AppShell pattern, but I have an idea that is a bit unconventional so I want to experiment with it first. I believe it can drop both the load time and adhere to the AppShell requirements. 

I can change the language on the title of the app if that helps: HNPWA Firebase (SSR Only) or something of the like.

Let me know if that sounds good to you.

**Comment by kristoferbaxter** [comment]
25ms DNS lookup is incredible.

I would love to pick your brain on hosting here, since this would reduce time to first byte for all the implementations significantly (for reference I see 450ms on most others).

**Comment by davideast** [comment]
@addyosmani Done! Let me know if that works for you.

@kristoferbaxter Let's definitely talk. I'd love to get the times down across the board. My approach leans heavily on Firebase Hosting's CDN. I serve HN API data through a CDN edge that is populated through a Cloud Function during after the `Cache-Control` period has expired. My app uses this API to generate the document and also stores that result in a CDN edge.

**Comment by addyosmani** [comment]
@davideast I'll probably play around with the labelling for this entry a little post-merging just to highlight it's an SSR-only app. Otherwise we're good to go here.

**Pull request merged**
