### PR TITLE
HNPWA with Vue.js hosted using Github Pages

### PR DESCRIPTION
**Pull request by anubhav7495**
Hi Everyone!

I would like to add my Vue.js implementation hosted using Github Pages.

[Link to Lighthouse Test](https://www.webpagetest.org/lighthouse.php?test=170711_ZB_a240146243587fb5c61017b0d9b588c3&run=2)

[Faster_3G](https://www.webpagetest.org/result/170711_ZB_a240146243587fb5c61017b0d9b588c3/)

[3G_Emerging_Markets](https://www.webpagetest.org/result/170711_CR_7d6edbaf1cfeb460324bc4ad71ba129d/)

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the submission! Just reviewed the performance traces and those LG from my end.

Going to check out navigating through the app for some of our other criteria next.

**Comment by addyosmani** [comment]
In-app experience and AppShell pattern appear to also be implemented as I would expect. Nice work 👍 .

**Comment by addyosmani** [comment]
Going to pass the buck to @housseindjirdeh or @chrisdwheatley in case they would like to provide a second opinion on this before we land it.

**Comment by housseindjirdeh** [comment]
This is great, everything LGTM :shipit: 

You did an outstanding job with this app  @anubhav7495  👍

**Pull request merged**
