### PR TITLE
Add Angular HN PWA

### PR DESCRIPTION
**Pull request by alfredoperez**
This Angular implementation uses ngu-pwa-tools library to create shell, manifest and firebase configuration

### CODE REVIEW

**Comment by anubhav7495** [comment]
@alfredoperez Nice Work man! Awesome app.

Some bugs that I noticed:

1. Clicking on `usernames` link does nothing and logs error to console.
2. Clicking on `comments` & `Ask HN` links also has the same error as `point-1` above.
3. **Minor**: Viewports below 360px causes header to overflow. Try `Nexus 5` or `iPhone 5` in Chrome dev-tools simulator to reproduce.
4. **Minor**: `serviceWorkerRegistration` is logged to console.
5. **Minor**: 100% width on the desktop makes the app a little inconvenient to use.

Thanks.

**Comment by alfredoperez** [comment]
Thanks @anubhav7495  for the great comments!

I will work on all the bugs!

**Comment by alfredoperez** [comment]
@anubhav7495 It is good to go now!
I also updated the PR

**Comment by anubhav7495** [comment]
@alfredoperez Nice work! I could find some new bugs this time around.

1. Clicking `Angular` icon should route to `Top` stories view but it goes to `New` stories views.
2. Pagination bar should be static just like the header. [Example](https://anubhav7495.github.io/hnpwa-vue/#/news)
3. I think you're re-rendering pagination bar on every route change, there is a better way to do it.
4. Possibly try to add a `Top` stories link in the header.
5. Post meta data should display `1 Point` instead of `1 Points`, just like you do for comment.
6. Header is unusable in 320px viewports. Try `iPhone 5` emulator in Chrome dev-tools.

Lighthouse scores check out perfectly.

Thanks.

**Comment by alfredoperez** [comment]
@anubhav7495 Fixed all the bugs =)
Please let me know what you think.
Thanks!

**Comment by anubhav7495** [comment]
@alfredoperez cool man!

@addyosmani Over to you.

**Comment by addyosmani** [comment]
Thanks so much for checking! The discrepancies you noted are a known and we’re working on addressing them upstream. In this case though I don't think that the differences we’re seeing in time to interactivity are particularly large between WPT and LH. This one should be good to go :)

image

**Pull request merged**
