### PR TITLE
Update ViperHTML bundler + timings

### PR DESCRIPTION
**Pull request by WebReflection**
viperHTML met Webpack today and it worked out pretty well 🎉

The timings updates are based on latest Lighthouse.

Best Regards.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
There appears to be a bit more variability in the numbers here, but definitely an improvement!

3G_EM: https://www.webpagetest.org/result/170628_7K_2f74d6fa5b2e887aa7399a09822107ef/
3G: https://www.webpagetest.org/result/170628_1F_a921740816c99dd5d0656efe83ca729e/

A small recommendation @WebReflection, looks like Brotli compression at q11 would drop the bundle for the main view /top/1 from 5.4KB to 4.8KB.

**Comment by kristoferbaxter** [comment]
I'm running the 3G_EM numbers a few more times too... be a few minutes.

**Comment by kristoferbaxter** [comment]
Ran two more tests at 3G_EM:

https://www.webpagetest.org/result/170628_76_0b6f99dcc6f417a27e540f1d3f09bbaa/ => 1.6
https://www.webpagetest.org/result/170628_SH_f11483f535825a9db9b5866e7d5fe582/ => 1.6

I'd say this looks good. Well done!

**Comment by TheLarkInn** [comment]
I saw 17 requests on initial load is that just the SW working in background thread and does that have an impact on normal connection load on em phones?

**Comment by kristoferbaxter** [comment]
That's correct, those are initiated by the SW and should not impact the main thread (from my understanding).

There is the potential for starvation of network resources, however these resources are requested with a medium priority.

**Comment by TheLarkInn** [comment]
I expected to see some more wins by cutting half of the upfront JS. I'm curious about the cieling or if it's less about the JavaScript now.

**Comment by WebReflection** [comment]
> Looks good to me, I might even suggest putting 1.6s as the interactive-em time.

@kristoferbaxter thanks for double checking. I've squashed changes updating 1.6s and links.

Going to sleep now, if anything I'll check tomorrow.

Regards

**Comment by WebReflection** [comment]
Hey @kristoferbaxter anything else I should do to merge this? Thanks

**Comment by kristoferbaxter** [comment]
Sorry, I'm out on paternity leave but I'd like for @addyosmani or @housseindjirdeh to take a look as well.

Merging with no sleep is a bad idea :)

**Comment by addyosmani** [comment]
There's something a little strange going on with the traces here testing https://viperhtml-164315.appspot.com/top/1. We're seeing FI and CI being reported very early on but the actual frames (where a user might click UI to interact with it) don't get painted until 1.9s.  

image

Looking at the WebPageTest run from a filmstrip view (which is going to have variance since it's a separate run to the Lighthouse report above), we see the first frames get painted at 2.5s with the main thread settling just a short while before that point:

**Comment by addyosmani** [comment]
There's something a little strange going on with the traces here testing https://viperhtml-164315.appspot.com/top/1 and reading the [Lighthouse report](https://www.webpagetest.org/lighthouse.php?test=170628_76_0b6f99dcc6f417a27e540f1d3f09bbaa&run=1). We're seeing FI and CI being reported early on but the actual frames (where a user might click UI to interact with it) don't get painted until 1.9s (from the Lighthouse strip below).  Is this expected, @tdresser @patrickhulce?

image

Looking at the WebPageTest run from a filmstrip view (which is going to have variance since it's a separate run to the Lighthouse report above), we see the first frames get painted at 2.5s with the main thread settling just a short while before that point:

image

[WebPageTest link](https://www.webpagetest.org/video/compare.php?tests=170628_SH_f11483f535825a9db9b5866e7d5fe582-r%3A2-c%3A0&thumbSize=200&ival=500&end=full)

We would love a confirmation on whether the Lighthouse filmstrip is just mismatching frames and that 1.6s number should be mostly reliable or whether this is another edge-case of the metrics needing further work.

**Comment by patrickhulce** [comment]
@addyosmani [from the trace](https://www.webpagetest.org/chrome/inspector-20170320/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?timeline=t:170628_76_0b6f99dcc6f417a27e540f1d3f09bbaa,r:lighthouse,c:0) it looks like there was considerable raster and GPU time that pushed out the screenshot you see on the timeline even though the layout for FMP happened at ~1600ms.

cc @spanicker who I believe was working with GPU folks to get this time included

**Comment by WebReflection** [comment]
CSS and layout haven't changed a single byte, how come all this is happening now? Previous numbers should have triggered the same concerns, right?

**Comment by patrickhulce** [comment]
Yeah the same issue applied to the [previous test](https://www.webpagetest.org/chrome/inspector-20170320/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?timeline=t:170613_FW_cef11c2c115a07b997263a2866203934,r:lighthouse,c:0) as well it probably wasn't noticed :) all FMP times (and therefore FI/CI) reported to this point suffer from the same skew, but some pages have more significant raster/GPU time that can make it more impactful.

image

**Comment by spanicker** [comment]
Yeah the paint timings are very close to getting updated in TBM and elsewhere 
Relevant bugs:
https://bugs.chromium.org/p/chromium/issues/detail?id=738235
https://bugs.chromium.org/p/chromium/issues/detail?id=738575

**Comment by WebReflection** [comment]
Should I just change my CSS then? Or ...is there anything I should really do at all? It looks like all numbers could be wrong in other PWAs too. I've copied most CSS by Svelte PWAs, as example. Does it have the same issue? I'm on my phone for few days and not sure how to double check, thanks.

**Comment by addyosmani** [comment]
> Should I just change my CSS then? Or ...is there anything I should really do at all?

That's a great question. We discovered a few areas that need improvement with our interactivity metrics that aren't Viper's fault at all. We've also seen some issues with them in the Ember and Next implementations below:

https://github.com/tastejs/hacker-news-pwas/pull/63
https://github.com/tastejs/hacker-news-pwas/pull/54

They're in a similar holding pattern. The two choices we've got to move this specific PR forward are:

1. Use a manually determined interactivity point (through trace inspection) of Viper's 3G and EM-3G runs. We could do that this week. 
2. Wait until Lighthouse is better able to capture TTI for these types of apps and update the PR at that point.

I've been encouraging authors to go with 1. with an issue filed for 2. so that you're not stalled. We're also planning on going back through the existing PWAs listed to verify TTI scores are fairly reflected across the base as we don't want to be showing favorable (if incorrect) scores for some vs others.

**Comment by WebReflection** [comment]
I'm on a road trip right now, incapable of testing much but I've read about GPU gotchas and I wonder if dropping all the transitions or special effects and lazy load those too would result in better metrics and less troubles for the GPU. After all, viperHTML here does 100% server side rendering and if lazy loading special FX is a way to improve, I'd like to know it myself and find out the best way to do that. Without client-side routing and transitions all those fade-in/out are useless, after all.

Thanks for suggestions or any extra clarification.

**Comment by tdresser** [comment]
@vmiura - any idea why the raster and GPU costs are so high on this page?

**Comment by addyosmani** [comment]
Friendly ping @vmiura. 

@WebReflection Could you confirm you would like us to keep this PR upon and not merge/edit scores based on a manual audit? I'm going through the PR queue and could land this sooner otherwise. Lighthouse hasn't fixed the issues we were seeing upstream yet.

**Comment by WebReflection** [comment]
I think I'd like to update scores once the issue is fixed and once I've eventually changed again viper-news code to better score in latest lighthouse.

You could close this if you want but please let me know when I can test again and trust results.

Thank you

**Comment by WebReflection** [comment]
Hello there!

I've done few changes to viper-news and these are my latest/updated results:

**3G EM** FI 1.6s
[WebPageTest](https://www.webpagetest.org/result/170801_WQ_77cd085f00f85ca6d755f358f0fee5de/)
[Lighthouse](https://www.webpagetest.org/lighthouse.php?test=170801_WQ_77cd085f00f85ca6d755f358f0fee5de&run=3)

**Fast 3G** FI 1.3
[WebPageTest](https://www.webpagetest.org/result/170801_NN_a1d5aaa01c5c210814b4cbeefd92bcc5/)
[Lighthouse](https://www.webpagetest.org/lighthouse.php?test=170801_NN_a1d5aaa01c5c210814b4cbeefd92bcc5&run=2)

Can I update this PR with these results? Or better, what's the current status in here?

Thanks for any sort of update.
Best Regards

**Comment by WebReflection** [comment]
P.S. I still see discrepancy between Lighthouse and WebPageTest

**3G EM**
screenshot from 2017-08-01 09-10-00


**Fast 3G**
screenshot from 2017-08-01 09-10-11

I guess nothing changed since last updates, am I correct?

**Comment by addyosmani** [comment]
@WebReflection Yeah nothing has (yet) changed I'm afraid. Those are discrepancies are still there :/

**Comment by WebReflection** [comment]
can I ask what was the reason to make it weight 25 and move it at the end of the list?

**Pull request merged**
