### PR TITLE
Add viperHTML to the list

### PR DESCRIPTION
**Pull request by WebReflection**
Mostly forked from Svelte HN version, the isomorphic [viperHTML](https://github.com/WebReflection/viperHTML) would like to join the list of blazing fast, Lighthouse friendly, possible library to create modern PWAs in a new, fully Web standard based, KISS way to update layouts.

### CODE REVIEW

**Comment by NekR** [comment]
@WebReflection to be fair requirement is 5 sec TTI and you said on twitter it's 5.12.<sup>[1]</sup> I know, I know, it's alfa :-) Anyway, I think it makes sense to add this, I'm pretty sure it will become faster soon.

><sup>[1]</sup> App must become interactive in under 5 seconds on a Moto G4 over 3G. Use WebPageTest to check.

**Comment by WebReflection** [comment]
I'm not sure I follow you. Which metrics are you using? 'cause I am using the Lighthouse one and time to interact is 529 **milliseconds** there.

screenshot from 2017-04-06 23-42-05

If you are talking about WTP then, have you checked others?

React: > 16.215s
Preact: > 5.896s
Svelte: > 4.585s
Vuew.js: > 8.609s
Angular: > 9.086s

vipdreHTML: > 4.511s

It wins in WPT ... I'm not sure it can be faster.

**Comment by NekR** [comment]
@WebReflection nevermind, sorry, I'm stupid today.

**Comment by addyosmani** [comment]
Thanks for the submission, @WebReflection!

Some quick notes:

Our readme asks to run the implementation through webpagetest.org/easy (it's what we link to). Here's a run of the app with those settings: https://www.webpagetest.org/result/170407_4A_5E5C/. Still interactive in <4s so good to go 👍 

Can you please update the TTI number in your commit to "3.3s"? See https://www.webpagetest.org/lighthouse.php?test=170407_4A_5E5C&run=2 for the Lighthouse report from a real phone.

Ignore the 85/100 in that report - you're fine on the HTTPS part of the audits. We have a bugfix waiting to be deployed for that in WebPageTest.

**Comment by WebReflection** [comment]
Apologies for the double change, I wasn't sure about changing the link too.

Actually, I am going to chang ethe link again so you can read the second run as well.

Please let me know if I should squash or we're good here, thank you!

**Comment by WebReflection** [comment]
Any obvious reason I'm missing to not merge this update?

**Comment by WebReflection** [comment]
Last change: there were few commits on the repo and more files to download as well as different approach for the SW.

I've updated the link with the latest run and the score, which is now 2.6s

https://github.com/tastejs/hacker-news-pwas/pull/6/commits/312ee749fd1a9e72ffacaa874eadd029a00d7124

**Comment by addyosmani** [comment]
Now that we've switched to GCE/AppEngine for the hosting, would you like to update the deployment links in your commit and latest timings?

**Comment by WebReflection** [comment]
done

**Comment by NekR** [comment]
@WebReflection @addyosmani why is it slower on `now`? `now`'s problem?

**Comment by WebReflection** [comment]
> now's problem?

it definitively had worse response time and it was also less reliable over random day/night access.

AppEngine is doing an awesome job so far 😉

**Comment by NekR** [comment]
@WebReflection I see, thanks. I saw such behavior, they apparently put apps on sleep and sometimes they cannot even recover.

**Comment by WebReflection** [comment]
it's like Heroku old dynos ... but worse.

They're new, let's hope they'll improve there 😄

**Comment by addyosmani** [comment]
LGTM to merge. Thanks, @WebReflection!

**Pull request merged**
