### PR TITLE
simplify GAE's url handlers

### PR DESCRIPTION
**Pull request by badersur**
based on https://cloud.google.com/appengine/docs/standard/python/getting-started/hosting-a-static-website I've tested it using `dev_appserver.py` & it's working fine :)

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Thank you so much for this!! Also tested this on a separate repository and it works perfectly 🎉 

One tiny thing: could you also remove the line in [CONTRIBUTING.md](https://github.com/tastejs/hacker-news-pwas/blob/master/CONTRIBUTING.md) that asks to add an entry to `app.yaml`? Once that's done we can definitely merge this in :)

**Comment by badersur** [comment]
You are welcome :smiley:
Line removed successfully :)

**Comment by housseindjirdeh** [comment]
Awesome thank you!! This makes so much more sense then having all the static files listed!

**Comment by badersur** [comment]
I agree :)

**Pull request merged**
