### PR TITLE
Add HNPWA - Micro - Mithril HN implementation

### PR DESCRIPTION
**Pull request by Masquerade-Circus**
Added HNPWA built with Mithril + Micro + Pure Material

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR!

Some UX feedback:

Mobile looks great. Desktop consumes a large portion of the available space, leaving users to have to move their cursor all the way to the left-hand-side to click a story.

image

Could we adopt the margin patterns used by the other apps? e.g

https://hn.svelte.technology/

image

Font-size is currently quite small (I found it harder to read without squinting). Could we consider bumping to 1em or similar?

image

Pagination: you've got pagination in there already which is great. Could we try to align the UX here slightly closer with how the other apps have approached this? (e.g prev [current/total] next) per https://react-hn.kristoferbaxter.com/ and https://angularhn.sebastian-mueller.net/list/top)

**Comment by Masquerade-Circus** [comment]
Thanks for the feedback. I've already made the adjustments and i've also drop the times:

interactive-em: 2.3s 
interactive-faster-3g: 1.9s
lighthouse-link: https://www.webpagetest.org/lighthouse.php?test=170801_W9_9ae8e32da50f560cd70cf5efeb85e1dc&run=2
wpt-em-link: https://www.webpagetest.org/result/170801_W9_9ae8e32da50f560cd70cf5efeb85e1dc/
wpt-faster-3g-link: https://www.webpagetest.org/result/170801_Y9_9fa3306c2ef9bbdf07000e42a2375edd/

I hope you can check it.

https://micro-mithril-hn.now.sh/

**Comment by addyosmani** [comment]
@Masquerade-Circus Thanks! If you have time, could we take a look at the color contrast notes from Lighthouse here?

image

I'm also seeing some issues with the pagination numbering if you get a chance:
image

For some reason comments are failing to render/look-up entirely atm:

https://micro-mithril-hn.now.sh/comments/15704730

image

**Comment by housseindjirdeh** [comment]
@Masquerade-Circus I'll be closing this as we've had it opened for some time, but please let us know if you interested in exploring fixing these minor issues and we can reopen this!

**Pull request closed without merging**
