### PR TITLE
Add more details to network settings used (#9)

### PR DESCRIPTION
**Pull request by addyosmani**
R: @housseindjirdeh @lukeed
issue: #9 

Wdyt? Is this better?

### CODE REVIEW

**Comment by lukeed** [comment]
I would also specify that the TTI results come from the Lighthouse reading. Admittedly, it took me a while to find that.

**Comment by addyosmani** [comment]
Would `Time To Interactive (Lighthouse):` solve that?

**Comment by lukeed** [comment]
Sure. Or for brevity, a third bullet point in the new **Network Settings** section with "Time to Interactive readings taken from linked Lighthouse results."

**Comment by addyosmani** [comment]
> Or for brevity, a third bullet point in the new Network Settings section with "Time to Interactive readings taken from linked Lighthouse results."

I like this suggestion! Let's do that!

**Comment by addyosmani** [comment]
Merging this first then landing that in a follow-up commit.

**Pull request merged**
