### PR TITLE
Add phone outline, re-shoot and process images

### LINKED ISSUE #14: Phone frame for site screenshots
Continuing the discussion from https://github.com/tastejs/hacker-news-pwas/issues/7#issuecomment-297613778

The question: 

> Just wondering, why are the phone mockups (Samsung phone, HTC phone) included as part of the site screenshots? I think would be better if just use a generic phone outline vector?

Additional concerns:

- Each site/app may seem *affiliated* to the phone brand/model?
- The screenshot images should be separated from the phone frame itself (in case we change to other phone frames or remove them later)

Possible solution(s):

- Change the phone frame to a generic one, or just an outline?

### PR DESCRIPTION
**Pull request by rl-king**
This PR fixes #14.

- Re-took screenshots of all implementations with Chrome on iPhone6-view and processed them all with `pngquant`. 
- Creates an outline of a generic modern smartphone with 44lines of Scss.
- Reduces network load on desktop (with images) from 7.2mb to 3.3mb. Which is still not really small. The height of the screenshots could be halved, but this would make them less nice on a hdpi display.

- _One issue with this PR might be that all current pull requests will have the 'wrong' image with a phone in it._ 
- _If you'd like I'll update the docs on how to take a screenshot_

screenshot
Example

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for sending over the set of changes. I think it would make a lot of sense for us to update the documentation so there is some guidance on how to take a screenshot.

@housseindjirdeh do you have any opinions on this direction?

**Comment by rl-king** [comment]
I think an explanation on how and with what settings you can take a screenshot with Chrome should suffice. Maybe requiring some post processing might be a bit much to ask as it requires someone to install some tools and figure out how they work.

**Comment by housseindjirdeh** [comment]
Thanks so much for this @rl-king, and apologies on my part for being hands off this project. I completely missed this.

I agree that this will pose an issue with all PRs coming in. @addyosmani and I are currently in the process of going through each of them so once that's done, I'll take this on.

Agreed on having a note for which device preset to use on DevTools. I'll add that as well!

**Comment by housseindjirdeh** [comment]
@rl-king thanks for all the help with this mate. I pulled down your branch and finished things up in a separate PR! #157 

Will close this in the meantime :) Thanks again for getting the ball rolling with this.

**Pull request closed without merging**
